#!/bin/bash

REF=${1:?"Usage: newbase <REF|number>"}
CUSTOM_EDITOR=${CUSTOM_EDITOR:-rebase_edit}

# If the first argument is a number, interpret it as an offset from the current HEAD
ONLY_DIGITS="^[0-9]+$"
if [[ "$1" =~ $ONLY_DIGITS ]]; then
    REF="HEAD~$REF"
fi;

GIT_EDITOR="${CUSTOM_EDITOR}" git rebase -i $REF

# Where are we now ...
git status
