name: CI
# Rename with 'name' input for manually triggered builds
run-name: ${{ github.event.inputs.name }}

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  # Manual trigger for release
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true
        default: 'snapshot'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2

      - run: opam install . --deps-only --with-test

      - name: Enforce source code formatting
        run: |
          opam exec -- make fmt-check
          
      - name: Tests
        run: |
          opam exec -- make test

      - name: Build executables
        run: |
          opam exec -- make build
          opam exec -- make install-newbase INSTALL_ROOT=.

      - name: Generate changelog
        if: github.event_name == 'workflow_dispatch'
        run: |
          opam exec -- make changelog-for-release

      - name: Release
        # Only if manually triggered
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.name }}
          target_commitish: main
          body_path: CHANGELOG_FOR_RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            newbase
            rebase_edit
